server:
  port: 8080
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
    instance:
      hostname: localhost

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: usuario-service
          #uri: lb://usuario-service
          uri: http://localhost:8001
          predicates:
            - Path=/usuario/**
        - id: carro-service
          #uri: lb://carro-service
          uri: http://localhost:8002
          predicates:
            - Path=/carro/**
        - id: moto-service
          #uri: lb://moto-service
          uri: http://localhost:8003
          predicates:
            - Path=/moto/**