server:
  port: 8081
Spring:
  cloud:
    config:
      server:
        git:
          default-label: circuit-breaker #config-server nombre de la rama  de git donde esta el config-server
          uri: https://github.com/mas2401master/microservice-spring-boot #url de git del proyecto 
          search-paths: config-data #direccion donde estan los archivos de configuracion de cada microservicio
  application:
    name: config-service #nombre de la aplicacion

  
